config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :pw

  email_regex = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :username,  :presence => true,
            :length               => { :maximum => 50}
  validates :email,     :presence => true,
            :format               => { :with => email_regex},
            :uniqueness           => { :case_sensitive => false}
  validates :pw,        :presence => true,
            :length               => { :within => 6..40}
  def has_password?(submitted_password)
    pw=submitted_password
  end
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)

    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def create
  user = User.authenticate(params[:session][:email], params[:session][:pw])

  if user.nil?
    flash.now[:error] = "Invalid Email/Password combo"
    render :new
  else
    sign_in user
    redirect_to user
  end
end

def destroy
  sign_out
  redirect_to new_session_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def user_params
        params.require(:user).permit(:username, :email, :pw)
  end
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :pw)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end

	def show
		
	end

	def new
		
	end

	def edit
		
	end

	def create
		
	end

	def destroy
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
      session[:user_id] = user.id
      self.current_user = user
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def signed_in?
        !current_user.nil?
    end

    def sign_out
        session[:user_id] = nil
        self.current_user = nil
    end

    def current_user?(user)
      user == current_user
    end

    def deny_access
      redirect_to signin_path, :notice => "please sign in to access this page."
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SLOG</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div id="wrapper">		
		<div id="main-nav">		
			<ul>
				<li><h3>SLOG</h3></li> |
				<li>Trails</li> |
				<li>Social</li> |
				<li>Forums</li> |
			</ul>
		</div>
	</div> <!--wrapper-->
	<h1>Editing User</h1>
	<div class="center">		

		<%= render 'form' %>

	
	</div>

	<div id="footer">
		<%= link_to 'Show', @user %> |
		<%= link_to 'Back', users_path %> |
		<%= link_to 'Home', root_path %>				
	</div>

</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SLOG</title>
</head>
<body>
  <div id="wrapper">
    <div id="main-nav">
      <ul>
        <li><h3>SLOG</h3></li> |
        <li><a href="#"> Trails </a></li> |
        <li><a href="#"> Social </a></li> |
        <li><a href="#"> Forum </a></li> |
      </ul>
    </div>
    <div id="header">
      <h1 id="logotype">SLOG</h1>
    </div>


    <div class="center">
      <h2>Listing Users</h2>
      <table>
        <thead>
          <tr>
            <th colspan="3"></th>
          </tr>
        </thead>
        <p id="notice"><%= notice %></p>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to '   Sign In  ', new_session_path %> | </td> 
              <td><%= link_to '   Show  ', user %> | </td> 
              <td><%= link_to '   Edit  ', edit_user_path(user) %> | </td> 
              <td><%= link_to '   Destroy  ', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div id="footer">
      <%= link_to 'New User', new_user_path %>
    </div>
  </div> <!--wrapper-->
</body>
</html>




<!--
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div id="wrapper">
		<div id="main-nav">
			<ul>
				<li><h3>SLOG</h3></li> |
				<li>Trails</li> |
				<li>Social</li> |
				<li>Forums</li> |
			</ul>
		</div>
	</div> <!--wrapper-->
	<div class="center">	
		<h1>Create Your Account</h1>
			<div class="form-container">
				<%= simple_form_for (@user) do |f| %>
				  <%= f.input :username %> </br>
				  <%= f.input :email %> </br>
				  <%= f.input :pw %> </br>
				  <%= f.button :submit %>
				<% end %>
			</div>
	</div>

	<div id="footer">
		<%= link_to 'Show', @user %> |
		<%= link_to 'Back', users_path %> |
		<%= link_to 'Home', root_path %>
	</div>

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div id="wrapper">
		<div id="main-nav">
			<ul>
				<li><h3>SLOG</h3></li> |
				<li>Trails</li> |
				<li>Social</li> |
				<li>Forums</li> |
			</ul>
		</div>
	</div> <!--wrapper-->
	<div class="center">
<h1>User <%= @user.id %></h1>
		<p id="notice"><%= notice %></p>
		<%= link_to('Sign Out', session_path, :method => :delete) %>
	</div>

	<div id="footer">
		<%= link_to 'Edit', edit_user_path(@user) %> |
		<%= link_to 'Back', users_path %> |
		<%= link_to 'Home', root_path %>
	</div>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SLOG</title>
</head>
<body>	
	<div id="wrapper">		
		<div id="main-nav">		
			<ul>
				<li><h3>SLOG</h3></li> |
				<li><a href="#"> Trails </a></li> |
				<li><a href="#"> Social </a></li> |
				<li><a href="#"> Forum </a></li> |
			</ul>
			
		</div>
		<div id="header">
			<h1 id="logotype">SLOG</h1>
		</div>
		
		<div class="center">			
			<div class="buttons">
				<%= link_to 'Find New Hikes!!', new_user_path %>
			</div>
			</br>
			<p><em>Not a member? Sign up below!</em></p>
			<div class="buttons">
				<%= link_to 'Sign Up to be a SLOG!!', new_user_path %>
			</div>
		</div>

		<div id="footer">
			
		</div>
	</div> <!--wrapper-->
</body>
</html>